# Generated by Django 5.1.4 on 2026-07-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katol_inventory_management', '0002_alter_sales_date_alter_stock_movement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('outdoor', 'OUTDOOR'), ('indoor', 'INDOOR'), ('low_smoke', 'LOW_SMOKE'), ('scented', 'SCENTED'), ('premium', 'PREMIUM'), ('value_pack', 'VALUE_PACK')], max_length=20),
        ),
    ]
